name: Detect Unexpected EE Changes

on:
  pull_request:
    paths-ignore:
      - COPYRIGHT
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
      - next/*
      - release/*
    paths-ignore:
      - COPYRIGHT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  detect-ee-changes:
    name: Detect EE Files and Copyright Header
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      # TODO: review permissions below
      # issues: read
      # checks: write
      # pull-requests: write
    if: (github.actor != 'dependabot[bot]')

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Get changed EE files
      id: changed-ee-files
      uses: kong/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf
      with:
        files: |
          spec-ee/**
          plugins-ee/**
          kong/enterprise_edition/**
          kong/plugins/**advanced**

    - name: Detect EE files
      if: steps.changed-ee-files.outputs.any_changed == 'true'
      run: |
        echo "The following unexpected EE files were detected:"
        echo "${{ steps.changed-ee-files.outputs.all_changed_files }}"
        exit 1

    - name: Get changed Lua files
      id: changed-files
      uses: kong/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf
      with:
        files: |
          **.lua

    - name: Detect copyright-header
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        scripts/no-copyright-header-checker.sh
